### ISSUE TITLE
Undefined variable "files" in Bio/DB/Sam.rb:28 in initialize

### ISSUE THREAD

**Issue by MatthewRalston** [helios/bioruby-samtools#45]
Found and fixed a teeny issue. Recently installed bio-samtools today, 2015/02/25 and encountered an error:

NameError: undefined local variable or method `files' for #<Bio::DB::Sam:0x00000001ecb868>
        from /home/mrals/.rvm/gems/ruby-2.1.2/gems/bio-samtools-2.3.0/lib/bio/db/sam.rb:28:in `initialize'
        from (irb):3:in `new'
        from (irb):3
        from /home/mrals/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'

This was resolved by inspecting the initialize method, at line 28, where the IOError refers to a "files" variable that was defined, and likely corresponds to the variable "@files." This fixed the error for me during initialization of a Bio::DB::Sam object. Cheers and thank you!

**Comment by danmaclean** [comment]
@homonecloco is this as a result of one of your changes? Shouldn't the unit tests have shown this? Let me know if you've any clues and I'll investigaye

**Comment by MatthewRalston** [comment]
Hi Dan, I did not change the source before I encountered this error. Also view the source for the initialize method on RubyDocs: http://www.rubydoc.info/gems/bio-samtools/Bio/DB/Sam#initialize-instance_method It includes a "files" variable that is not defined during initialization. Try loading a file that doesn't exist and you will encounter it.

**Comment by homonecloco** [comment]
Thanks for reporting it @MatthewRalston , it is a bug in the error message. it is likely that one of the paths is wrong. 
@danmaclean , it is not related to the changes I´m currently doing, those are in my repository (to avoid introducing bugs in the main repo). The bug is not covered as there are no unit tests for the initialisation of the object and that it rises the expected exception. I´ll patch the code. 
R.

**Comment by homonecloco** [comment]
@MatthewRalston , feel free to reopen the issue if the patch didn´t fix the issue.
